# from Kata import bit_counting
# from Kata import collatz_conjecture
# from Kata import complementary_dna
# from Kata import convert_a_hex_string_to_rgb
# from Kata import count_the_smiley_faces
# from Kata import delete_occurrences_of_an_element_if_it_occurs_more_than_n_times
# from Kata import equal_sides_of_an_array
# from Kata import extract_the_domain_name_from_a_url
# from Kata import find_the_odd_int
# from Kata import first_non_repeating_character
# from Kata import isograms
# from Kata import moving_zeros_to_the_end
# from Kata import multiples_of_3_or_5
# from Kata import replace_with_alphabet_position
# from Kata import rgb_to_hex_conversion
# from Kata import stop_gninnips_my_sdrow
# from Kata import who_likes_it
# from Kata import youre_a_square
